version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test
      - rm -rf ./__tests__
      - npm prune --production
  build:
    commands:
      - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
